version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: xcommerce_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - xcommerce_net

networks:
  xcommerce_net:
    driver: bridge

volumes:
  db_data:
    driver: local
